version: '3.8'

services:
  backend:
    build:
      context: ./back
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./front
    ports:
      - "3000:3000"

  database:
    build:
      context: ./db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root