version: '3.8'

services:
  operations_db:
    container_name: operations_db
    build: ./db
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: operations
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"] # Prueba de ping a la base de datos
      interval: 10s  # Intervalo entre pruebas
      retries: 5     # Número de intentos antes de marcar el contenedor como no saludable
      timeout: 5s    # Tiempo de espera para cada prueba

  backend:
    container_name: backend
    build:
      context: ./back
    depends_on:
      operations_db:
        condition: service_healthy
    ports:
      - "8080:8080"

  frontend:
    container_name: frontend
    build:
      context: ./front
    ports:
      - "3000:3000"