version: '3.8'

services:
  operations_db:
    container_name: operations_db
    build: ./db
    image: operations_db
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: operations
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root","-p root"]
      timeout: 20s
      retries: 10

  backend:
    container_name: backend
    build:
      context: ./back
    image: backend
    depends_on:
      operations_db:
        condition: service_healthy
    ports:
      - "8080:8080"

  frontend:
    container_name: frontend
    build:
      context: ./front
    image: frontend
    depends_on:
      backend:
        condition: service_started
    ports:
      - "3000:3000"