version: '3.8'

services:
  operations_db:
    container_name: operations_db
    build: ./db
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: operations
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"

  backend:
    container_name: backend
    build:
      context: ./back
    depends_on:
      operations_db:
        condition: service_started
    ports:
      - "8080:8080"

  frontend:
    container_name: frontend
    build:
      context: ./front
    ports:
      - "3000:3000"