name: CI/CD Workflow

on:
  workflow_dispatch:

jobs:
  build_test_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build images
      run: |
        docker-compose build

    - name: start containers
      run: |
        docker-compose up -d
        
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
        
    - name: Execute test file
      run: |
        docker exec backend go test -v ./service

    - name: Stop containers
      run: |
        docker-compose down

    - name: Login to DockerHub
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
        
    - name: Tag images
      run: |
        docker tag backend:latest ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
        docker tag frontend:latest ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
        docker tag operations_db:latest ${{ secrets.DOCKERHUB_USERNAME }}/operations_db:latest
      
    - name: Push images
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/operations_db:latest
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Configure gcloud CLI
      uses: google-github-actions/setup-gcloud@v0.5.0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

    - name: Login to DockerHub
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Download Docker images
      run: |
        docker pull aguszanini/backend:latest
        docker pull aguszanini/frontend:latest
        docker pull aguszanini/operations_db:latest
    
    - name: Run Docker db container to extract SQL file
      run: |
        docker run --rm aguszanini/operations_db:latest sh -c 'cp operations.sql ./'

    - name: Upload SQL file to Cloud Storage
      run: gsutil cp ./operations.sql gs://bd_temp

    - name: Tag backend and frontend Docker images
      run: |
        docker tag backend:latest gcr.io/finalingsoft3/backend:latest
        docker tag frontend:latest gcr.io/finalingsoft3/frontend:latest

    - name: Push backend and frontend Docker images to Google Container Registry
      run: |
        docker push gcr.io/finalingsoft3/backend:latest
        docker push gcr.io/finalingsoft3/frontend:latest
        
    - name: Import SQL file to Cloud SQL
      run: |
        gcloud sql import sql finalingsoft3bd gs://bd_temp/operations.sql

    - name: Deploy backend and frontend to Google Cloud Run
      run: |
        gcloud run deploy backend --image gcr.io/finalingsoft3/backend:latest --port=8080 --platform managed --region=us-central1 --allow-unauthenticated --max-instances=15
        gcloud run deploy frontend --image gcr.io/finalingsoft3/frontend:latest --port=3000 --platform managed --region=us-central1 --allow-unauthenticated --max-instances=15
