name: deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Configure gcloud CLI
      uses: google-github-actions/setup-gcloud@v0.5.0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

        
    - name: Configure Docker for Container Registry
      run: |
        gcloud auth configure-docker

    - name: Login to DockerHub
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Download Docker images
      run: |
        docker pull aguszanini/backend:latest
        docker pull aguszanini/frontend:latest
        docker pull aguszanini/operations_db:latest
    
    - name: Run Docker db container to extract SQL file
      run: |
        docker create --name temp-container aguszanini/operations_db:latest
        docker cp temp-container:/docker-entrypoint-initdb.d/operations.sql ./operations.sql
        docker rm temp-container

    - name: Upload SQL file to Cloud Storage
      run: gsutil cp ./operations.sql gs://bd_temp

    - name: Tag backend and frontend Docker images
      run: |
        docker tag aguszanini/backend:latest gcr.io/finalingsoft3/backend:latest
        docker tag aguszanini/frontend:latest gcr.io/finalingsoft3/frontend:latest

    - name: Push backend and frontend Docker images to Google Container Registry
      run: |
        docker push gcr.io/finalingsoft3/backend:latest
        docker push gcr.io/finalingsoft3/frontend:latest
        
    - name: Import SQL file to Cloud SQL
      run: |
        gcloud sql import sql finalingsoft3bd gs://bd_temp/operations.sql

    - name: Deploy backend and frontend to Google Cloud Run
      run: |
        gcloud run deploy backend --image gcr.io/finalingsoft3/backend:latest --port=8080 --platform managed --region=us-central1 --allow-unauthenticated --max-instances=15
        gcloud run deploy frontend --image gcr.io/finalingsoft3/frontend:latest --port=3000 --platform managed --region=us-central1 --allow-unauthenticated --max-instances=15
