name: integration_tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install CodeceptJS
      run: npm install codeceptjs@3.5.13-beta.3
  
    - name: Update Dependencies
      run: npm update
  
    - name: Install playwright
      run: |
        cd integration_tests
        npm install --save-dev playwright@^1.18
        
    - name: Install playwright browsers
      run: |
        cd integration_tests
        npx playwright install

    - name: Execute integration tests
      run: |
        cd integration_tests
        npx codeceptjs run --steps
