name: integration_tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Asegúrate de usar la versión de Node.js que sea compatible con tu proyecto

    - name: Instalar dependencias
      run: |
        cd integration_tests
        npm ci

    - name: Ejecutar pruebas de CodeceptJS
      run: npx codeceptjs run --steps
