name: CI/CD Workflow

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build images
      run: |
        docker-compose build
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
        
    - name: Execute test file
      working-directory: ./finalingsoft3/back/service
      run: |
        pwd
        go test -v
  publish:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Login to DockerHub
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
        
    - name: Tag images
      run: |
        docker tag backend:latest ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
        docker tag frontend:latest ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
        docker tag database:latest ${{ secrets.DOCKERHUB_USERNAME }}/database:latest
      
    - name: Push images
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/database:latest
