name: CI/CD Workflow

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build_test_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build images
      run: |
        docker-compose build

    - name: start containers
      run: |
        docker-compose up -d
        
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
        
    - name: Execute test file
      run: |
        docker exec backend go test -v ./service

    - name: Stop containers
      run: |
        docker-compose down

    - name: Login to DockerHub
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
        
    - name: Tag images
      run: |
        docker tag backend:latest ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
        docker tag frontend:latest ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
        docker tag operations_db:latest ${{ secrets.DOCKERHUB_USERNAME }}/operations_db:latest
      
    - name: Push images
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/operations_db:latest
