name: CI/CD Workflow

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and test
      run: |
        docker-compose build
        docker-compose exec backend go test -v ./service

  publish:
    needs: build_and_test
    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Tag and push Docker images
      run: |
        docker tag backend ${{secrets.DOCKERHUB_USERNAME }}/backend
        docker tag frontend ${{secrets.DOCKERHUB_USERNAME }}/backend
        docker tag operations_db ${{secrets.DOCKERHUB_USERNAME }}/operations_db
        
        docker push ${{secrets.DOCKERHUB_USERNAME }}/backend
        docker push ${{secrets.DOCKERHUB_USERNAME }}/frontend
        docker push ${{secrets.DOCKERHUB_USERNAME }}/operations_db
